name: Android CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  build:
    # Define the environment for the job
    runs-on: ubuntu-latest

    # Set up the steps for the job
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 (or use the version compatible with your project)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Temurin distribution (formerly AdoptOpenJDK)
          java-version: '11'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Download and setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33            # API level of the Android SDK
          build-tools: 33.0.0       # Version of the build tools
          target: default           # Emulator target (optional if not running emulator)
          components: platform-tools # Platform tools needed for the build

      # Grant execution permissions to Gradle wrapper
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Build the project
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Optionally, run tests
      - name: Run unit tests
        run: ./gradlew test
